"""
AntiFake — AI Video Authenticity Detector

Hugging Face Spaces entrypoint.
Runs the 7-detector forensic ensemble through ZeroGPU.
"""

import os
import logging

import gradio as gr
import spaces

from poc_runtime import analyze_video


# ---------------------------------------------------------
# Logging
# ---------------------------------------------------------

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# Video processing
# ---------------------------------------------------------

@spaces.GPU
def process_video(video_file: str) -> dict:
    """
    Analyze an uploaded video using the AntiFake
    forensic detection pipeline.

    The entire inference pipeline runs inside the
    ZeroGPU allocation.
    """

    if video_file is None:
        return {
            "error": "No video file provided"
        }

    logger.info("[Gradio] Analyzing video: %s", video_file)

    try:
        results = analyze_video(video_file)

        logger.info(
            "[Gradio] Analysis complete — "
            "score: %s, confidence: %s",
            results.get("score", "N/A"),
            results.get("confidence", "N/A"),
        )

        return results

    except Exception as exc:
        logger.exception("[Gradio] Analysis failed")

        return {
            "score": 0.0,
            "confidence": 0.0,
            "summary": f"Analysis failed: {str(exc)}",
            "detectors": {},
            "error": str(exc),
        }


# ---------------------------------------------------------
# Gradio interface
# ---------------------------------------------------------

demo = gr.Interface(
    fn=process_video,

    inputs=gr.Video(
        label="Upload Video (MP4, WebM, MOV, AVI)"
    ),

    outputs=gr.JSON(
        label="Forensic Analysis Results"
    ),

    title="🛡️ AntiFake — AI Video Detector",

    description=(
        "Upload a video to detect if it was generated by "
        "AI models like Sora, Kling, Hailuo, Runway, Luma, "
        "Pika, or Seedance. Uses a 7-detector forensic ensemble: "
        "CLIP, Optical Flow, PRNU Noise, Temporal Consistency, "
        "FFT Spectral, Compression, and VideoMAE."
    ),

    article=(
        "**How it works:** The system extracts frames from your "
        "video and runs them through 7 independent forensic "
        "detectors. Results are fused using a non-linear "
        "overrule engine where physical forensics (noise, flow, "
        "temporal) can override visual models fooled by "
        "photorealism.\n\n"
        "**Privacy:** Videos are processed in memory and deleted "
        "immediately after analysis."
    ),

    examples=[],
    cache_examples=False,
    analytics_enabled=False,
)


# ---------------------------------------------------------
# Application startup
# ---------------------------------------------------------

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "7860"))

    demo.launch(
        server_name="0.0.0.0",
        server_port=port,
    )