"""
AntiFake — AI Video Authenticity Detector (Gradio Interface)

This is the entrypoint for Hugging Face Spaces (Gradio SDK).
It wraps the 7-detector forensic ensemble from poc_runtime.py
in a Gradio UI that also exposes a programmatic API at /api/predict.

The backend (on Render) calls this Space via the `gradio_client` library.
Users can also interact with it directly through the Gradio web UI.
"""

import gradio as gr
import json
import logging
import os

from poc_runtime import analyze_video

logging.basicConfig(level=logging.INFO)


def process_video(video_file: str) -> dict:
    """
    Process an uploaded video through the full 7-detector forensic ensemble.

    Args:
        video_file: Path to the uploaded video file (Gradio handles the upload).

    Returns:
        dict with score, confidence, summary, and per-detector breakdown.
    """
    if video_file is None:
        return {"error": "No video file provided"}

    logging.info(f"[Gradio] Analyzing video: {video_file}")

    try:
        results = analyze_video(video_file)
        logging.info(
            f"[Gradio] Analysis complete — "
            f"score: {results.get('score', 'N/A')}, "
            f"confidence: {results.get('confidence', 'N/A')}"
        )
        return results
    except Exception as e:
        logging.error(f"[Gradio] Analysis failed: {e}")
        return {
            "score": 0.0,
            "confidence": 0.0,
            "summary": f"Analysis failed: {str(e)}",
            "detectors": {},
        }


# ── Gradio Interface ──────────────────────────────────────────────

demo = gr.Interface(
    fn=process_video,
    inputs=gr.Video(label="Upload Video (MP4, WebM, MOV, AVI)"),
    outputs=gr.JSON(label="Forensic Analysis Results"),
    title="🛡️ AntiFake — AI Video Detector",
    description=(
        "Upload a video to detect if it was generated by AI models like "
        "Sora, Kling, Hailuo, Runway, Luma, Pika, or Seedance. "
        "Uses a 7-detector forensic ensemble: CLIP, Optical Flow, PRNU Noise, "
        "Temporal Consistency, FFT Spectral, Compression, and VideoMAE."
    ),
    article=(
        "**How it works:** The system extracts frames from your video and runs "
        "them through 7 independent forensic detectors. Results are fused using "
        "a non-linear overrule engine where physical forensics (noise, flow, "
        "temporal) can override visual models fooled by photorealism.\n\n"
        "**Privacy:** Videos are processed in memory and deleted immediately after analysis."
    ),
    examples=[],
    cache_examples=False,
    analytics_enabled=False,
)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "7860"))
    demo.launch(server_name="0.0.0.0", server_port=port)
