# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_detector_pb2 as video__detector__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoDetectorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeVideo = channel.unary_unary(
                '/video_detector.VideoDetectorService/AnalyzeVideo',
                request_serializer=video__detector__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=video__detector__pb2.AnalyzeResponse.FromString,
                _registered_method=True)


class VideoDetectorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeVideo(self, request, context):
        """Analyzes a video and returns authenticity scores.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoDetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeVideo,
                    request_deserializer=video__detector__pb2.AnalyzeRequest.FromString,
                    response_serializer=video__detector__pb2.AnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_detector.VideoDetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video_detector.VideoDetectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoDetectorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_detector.VideoDetectorService/AnalyzeVideo',
            video__detector__pb2.AnalyzeRequest.SerializeToString,
            video__detector__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
